### ISSUE TITLE
Paginator numbers location error

### ISSUE THREAD

**Issue by thiagojeffery** [elboletaire/twbs-cake-plugin#12]
* BootstrapUI Version: 0.62

I baked the index and the Paginator->Numbers was not between "First and Last".

The code for PaginatorHelper is:
public function numbers(array $options = [])
    {
        $class = 'pagination';
        $options += [
            'class' => $class,
            'after' => '</ul>',
            'size' => null,
        ];
        $options['class'] = implode(' ', (array)$options['class']);
        if (!empty($options['size'])) {
            $options['class'] .= " {$class}-{$options['size']}";
        }
        $options += [
           'before' => '<ul class="' . $options['class'] . '">',
        ];

To fix it I did:
public function numbers(array $options = [])
    {
        $class = 'pagination';
        $options += [
            'class' => $class,
            //'after' => '</ul>',
            'size' => null,
        ];
        $options['class'] = implode(' ', (array)$options['class']);
       if (!empty($options['size'])) {
            $options['class'] .= " {$class}-{$options['size']}";
        }
        $options += [
            //'before' => '<ul class="' . $options['class'] . '">',
        ];

**Comment by elboletaire** [comment]
The `PaginatorHelper` is part of the [BootstrapUI][bootstrap-ui] package. [Open an issue there][bootstrap-ui issues] if you think there's one with their helper.

[bootstrap-ui]: https://github.com/FriendsOfCake/bootstrap-ui/
[bootstrap-ui issues]: https://github.com/FriendsOfCake/bootstrap-ui/issues
