### ISSUE TITLE
Flash error

### ISSUE THREAD

**Issue by Perzonallica** [elboletaire/twbs-cake-plugin#4]
Hi!
I'm using the newest version (RC1) of CakePHP. I'm getting on every view this error message:

```Warning (512): Method Cake\View\Helper\SessionHelper::flash does not exist [CORE/src/View/Helper.php, line 138]```

I changed this line: ```<?= $this->Session->flash(); ?>``` to ```<?= $this->Flash->render() ?>``` but it doesn't seems to be resolved:

```Notice (8): Undefined variable: class [ROOT/plugins/Bootstrap/src/Template/Element/flash.ctp, line 3]" role="alert">  ×Close The user has been saved.```

**Comment by Perzonallica** [comment]
Yes, it's enabled.
I think the problem is with the $class variable in this line:
```<div class="alert <?php if ($is_closable) echo 'alert-dismissable '; ?>alert-<?php echo $class ?>" role="alert">```

If I manually rewrite it to this: alert-danger, then it works.

**Comment by elboletaire** [comment]
How are you setting the flash alert?

It must be set like so:

```php
$this->Flash->error("Your error message");
$this->Flash->info("Your info message");
$this->Flash->whateverClassNameYouWantToSet();
```

**Comment by Perzonallica** [comment]
Yes, I have it that way.

**Comment by elboletaire** [comment]
Hhuum, that's weird... then let me take a further look into it because I'm currently at work and I should be doing other things. :stuck_out_tongue:

**Comment by Perzonallica** [comment]
Hehe, yeah OK. ;)

**Comment by elboletaire** [comment]
Now there's no need to pass params in a `params` key to the flash element. That's why this was failing.

Is the second time that CakePHP developers have changed this since they started with CakePHP 3.0... hopefully the last time.

Thanks for the report @Perzonallica :smile:

**Comment by Perzonallica** [comment]
Great news! Thank you for your time! :)

**Comment by adam-je** [comment]
I was wrestling with this til I loaded Flash in **AppController** as such:

public function initialize() {
    $this->loadComponent('Bootstrap.Flash');
}

**Comment by elboletaire** [comment]
Well, that comes with a default CakePHP 3 installation. That's why it's not added to the readme.

You can see it in the current master branch of CakePHP: https://github.com/cakephp/app/blob/master/src/Controller/AppController.php#L42 It is not a recent change... so you probably removed it accidentally or maybe you are working with a very outdated version of CakePHP. In that case you should consider updating.
