### ISSUE TITLE
question about customization

### ISSUE THREAD

**Issue by CodeBlastr** [elboletaire/twbs-cake-plugin#9]
In the default template there is this code:

``` php
<?php if ($this->fetch('navbar.top')): ?>
            <nav role="navigation" class="collapse navbar-collapse" id="navbar-top">
                <ul class="nav navbar-nav">
                    <?= $this->fetch('navbar.top'); ?>
                </ul>
            </nav>
<?php endif; ?>
```

I've searched and searched through cakephp documentation and I'm not seeing the best way to create a default navbar.top value.  I understand $this->extend(), but with my tests so far you can't seem to extend a layout with another layout. So trying to do something like `$this->extend('/Layout/default');` doesn't work. If there was like `if element exists` type of code in your default layout, that would seem to be idea, but since that's not what it is...  I'm just wondering what do you consider the best practice for creating a default navbar using your default layout?

**Comment by elboletaire** [comment]
Someone asked the same on stackoverflow:

http://stackoverflow.com/questions/29404697/where-do-i-set-the-navbar-in-cakephp-3-0-with-bootstrap/29637981#29637981

I should add more documentation about this (don't close the issue, I'll use this as a remember).

**Comment by elboletaire** [comment]
BTW, you can extend a layout using another layout.. that's one of the magics of `extend`.

**Comment by CodeBlastr** [comment]
I imagine you can extend a layout with another layout, but I guess I'm not sure what path to put in the extend function to get it to work and/or where to put the layout file you want to over ride it with. 

I suppose that's really the info I'm looking for.  For example, I tried to create a ``APP/src/Template/Layout/default.ctp``, and put a bunch of variations on something like this ``$this->extend('/Bootstrap.Layout/default');`` into it without any luck.  Just errors about cake not finding the layout that was trying to be extended.

**Comment by CodeBlastr** [comment]
BTW, if you drop a little info on me regarding the above, I'll make a pull request on the readme file and update it with some new info and save you some time.

**Comment by elboletaire** [comment]
Sorry I forgot to say that using View's `extend` method does not work for plugins nor vendors.

You should copy the desired layout to your `Layout` folder and then you'll can.

Plugin notation only works using `$this->layout` (in `AppView` or directly on the view file)..

**Comment by ADmad** [comment]
> Sorry I forgot to say that using View's extend method does not work for plugins nor vendors.

You can, `$this->extend('Bootstrap./Layout/default');`.
